name = "cuttingasmr-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

# Cloudflare Pages 环境变量
[env.production.vars]
NODE_ENV = "production"
# 确保使用生产环境配置，不使用测试模式
CREEM_TEST_MODE = "false"
# 生产环境域名
NEXT_PUBLIC_APP_URL = "https://cuttingasmr.org"
# Creem生产环境配置 - 需要在Cloudflare Pages设置中配置实际值
# CREEM_API_KEY = "creem_4bO7LLLWie17BD2i7qTNNA"  # 在Cloudflare Pages中设置
# CREEM_WEBHOOK_SECRET = "whsec_6jovyxtbgdcdNEMdH0nspT"  # 在Cloudflare Pages中设置 