export default function Head() {
  return (
    <>
      <title>AI Veo3 Video & AI Prompt Gallery | Best Veo3 AI Video Prompt Templates</title>
      <meta
        name="description"
        content="Discover professional AI videos generated by Google Veo3 and copy the exact prompt templates to create your own stunning content. Browse our Veo3 video gallery for tested, optimized AI video prompts ready for YouTube, TikTok and more."
      />
    </>
  );
} 