import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'AI Veo3 Video & AI Prompt Gallery | Best Veo3 AI Video Prompt Templates',
  description: 'Discover professional AI videos generated by Google Veo3 and copy the exact prompt templates to create your own stunning content. Browse our Veo3 video gallery for tested, optimized AI video prompts ready for YouTube, TikTok and more.',
  alternates: {
    canonical: 'https://cuttingasmr.org/video-showcase'
  },
  keywords: 'google veo3, veo3 prompts, ai video templates, video prompts, google veo3 gallery, ai video generator prompts, veo3 examples, video creation prompts, ai content templates, professional ai videos, veo3 video prompt, ai video prompt',
  openGraph: {
    title: 'AI Veo3 Video & AI Prompt Gallery | Best Veo3 AI Video Prompt Templates',
    description: 'Discover professional AI videos generated by Google Veo3 and copy the exact prompt templates to create your own stunning content.',
    url: 'https://cuttingasmr.org/video-showcase',
    type: 'website',
    images: [
      {
        url: 'https://cuttingasmr.org/logo.svg',
        width: 1200,
        height: 630,
        alt: 'AI Veo3 Video Gallery',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'AI Veo3 Video & AI Prompt Gallery',
    description: 'Discover professional AI videos generated by Google Veo3 and copy the exact prompt templates.',
  }
}

export default function VideoShowcaseLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>
} 