import { ShowcaseVideo, VideoCategory } from './video-types';

// 腾讯云ASMR视频集合 - Google Veo3 AI生成的专业ASMR视频
export const showcaseVideos: ShowcaseVideo[] = [
  {
    id: 'planet-cutting-1',
    title: 'Planet Cutting ASMR Al Video',
    description: 'Experience cosmic planet cutting with Google Veo3 AI technology. Perfect for YouTube shorts and TikTok videos. This AI-generated ASMR video features mesmerizing space textures and otherworldly sound effects created with advanced text-to-video AI.',
    prompt: 'Realistic 4K footage close-up of a knife cutting a [COLOR] [MATERIAL] [Planet] on a [SURFACE]. It slices it single time, The gloved hands then gently pull apart the halves. Slice is [Material] [Effect]. The inside of the [OBJECT] is [Status]. The sound is ASMR style.',
    thumbnailUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87%E5%89%B2%E6%98%9F%E7%90%83%E8%A1%8C%E6%98%9F.mp4',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87%E5%89%B2%E6%98%9F%E7%90%83%E8%A1%8C%E6%98%9F.mp4',
    duration: '1:05',
    category: 'satisfying',
    asmrType: 'Planet Cutting',
    featured: true,
    createdAt: '2024-12-27T15:00:00Z',
    viewCount: 2847,
    tags: ['planet', 'space', 'cosmic', 'cutting', 'veo3', 'ai-video', 'youtube-shorts', 'tiktok']
  },
  {
    id: 'glass-vegetable-cutting-1',
    title: 'Glass Vegetable Cutting ASMR AI Video',
    description: 'Delicate glass vegetable cutting created with AI video maker technology. Perfect satisfying content for TikTok shorts and YouTube videos. Features crystal-clear knife cutting sounds and beautiful translucent textures generated by Google Veo3 AI.',
    prompt: 'Realistic 4K footage close-up of a knife rapidly cutting a [COLOR] [MATERIAL] [OBJECT] on a wooden cuttingboard. It slices it multiple times, each slice falls over as the knife moves to the next. The inside of the [OBJECT] is also [MATERIAL]. The sound is ASMR style.',
    thumbnailUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87%E5%89%B2%E7%8E%BB%E7%92%83%E8%94%AC%E8%8F%9C.mp4',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87%E5%89%B2%E7%8E%BB%E7%92%83%E8%94%AC%E8%8F%9C.mp4',
    duration: '0:58',
    category: 'crystal',
    asmrType: 'Glass Cutting',
    featured: true,
    createdAt: '2024-12-27T14:30:00Z',
    viewCount: 3156,
    tags: ['glass', 'vegetable', 'crystal', 'cutting', 'knife', 'ai-asmr', 'youtube-shorts', 'tiktok-shorts']
  },
  {
    id: 'animal-diving-1',
    title: 'Animal Diving AI Video - Google Veo3 Al',
    description: 'Mesmerizing animal diving scenes created with Google Veo3 AI technology. Perfect for YouTube shorts and TikTok videos. Features soothing water sounds and graceful animal movements. This AI-generated ASMR video showcases peaceful aquatic scenes for ultimate relaxation.',
    prompt: 'Televised footage of a majestic [grey elephant] performing a high-dive from the 10-meter platform at the Olympics, in a grand, modern indoor aquatics stadium with multiple diving boards and a vibrant blue pool. The atmosphere is electrifying, with a massive, cheering and applauding crowd filling the stands. The style is cinematic and photorealistic broadcast footage, featuring slow-motion replays of the elephant\'s powerful leap and colossal splash, dynamic camera angles capturing the dive from multiple perspectives, and immediate crowd reactions of awe and excitement. The scene includes scoreboards displaying humorous scores, and the intense anticipation and celebration of a major sporting event.',
    thumbnailUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%8A%A8%E7%89%A9%E8%B7%B3%E6%B0%B4.mp4',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%8A%A8%E7%89%A9%E8%B7%B3%E6%B0%B4.mp4',
    duration: '1:15',
    category: 'nature',
    asmrType: 'Animal Diving',
    featured: true,
    createdAt: '2024-12-27T16:00:00Z',
    viewCount: 1245,
    tags: ['animals', 'diving', 'water', 'nature', 'veo3-asmr', 'ai-videos', 'youtube-shorts', 'tiktok', 'relaxing']
  },
  {
    id: 'cosmic-cutting-1',
    title: 'Cosmic Nebula Cloud Cutting ASMR AI Video',
    description: 'Experience mesmerizing cosmic nebula cutting created with Google Veo3 AI technology. Perfect for YouTube shorts and TikTok videos. Features ethereal space sounds and stunning visual effects. This AI-generated ASMR video showcases the best of what AI ASMR can create with advanced text-to-video technology.',
    prompt: 'Realistic 4K footage close-up of a knife cutting a [COLOR] [MATERIAL] [NEBULA] on a [SURFACE]. It slices it multiple times. Slice is [Material] [Effect]. The inside of the [OBJECT] is also [MATERIAL], And each slice has [Special Effects]. The sound is ASMR style.',
    thumbnailUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87%E5%89%B2%E6%98%9F%E4%BA%91%E3%80%81%E4%B9%8C%E4%BA%91.mp4',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87%E5%89%B2%E6%98%9F%E4%BA%91%E3%80%81%E4%B9%8C%E4%BA%91.mp4',
    duration: '1:10',
    category: 'satisfying',
    asmrType: 'Cosmic Cutting',
    featured: true,
    createdAt: '2024-12-27T11:00:00Z',
    viewCount: 1337,
    tags: ['cosmic', 'nebula', 'cutting', 'space', 'veo3-asmr', 'ai-videos', 'youtube-shorts', 'tiktok']
  },
  {
    id: 'squeeze-toy-1',
    title: 'Slime Toy ASMR',
    description: 'Satisfying slime toy ASMR created with best AI video generator. Perfect for YouTube shorts and TikTok content creation. Features soft textures and gentle pressure sound effects generated by Google AI technology for ultimate relaxation.',
    prompt: 'A pair of hands repeatedly touches a lump of [color/fluorescent] slime toy on a wooden surface. The sound is ASMR style.',
    thumbnailUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E6%8D%8F%E6%8D%8F%E4%B9%90.mp4',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E6%8D%8F%E6%8D%8F%E4%B9%90.mp4',
    duration: '0:52',
    category: 'texture',
    asmrType: 'Slime Toy',
    featured: true,
    createdAt: '2024-12-26T14:00:00Z',
    viewCount: 1456,
    tags: ['slime', 'texture', 'soft', 'ai-video-maker', 'youtube-shorts']
  },
  {
    id: 'digital-product-cutting-1',
    title: 'Digital Product Cutting ASMR AI Video',
    description: 'Precise cutting sounds of digital devices created with advanced AI video generator. Perfect for creating AI videos and TikTok shorts. Features crisp electronic textures and satisfying knife cutting sounds generated by Google Veo3.',
    prompt: 'Realistic 4K footage close-up of a knife cutting a [COLOR] [Digital products] on a wooden surface. It slices it multiple times. Inside each slice are electronic components exposed. The sound is ASMR style.',
    thumbnailUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87%E6%95%B0%E7%A0%81%E4%BA%A7%E5%93%81.mp4',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87%E6%95%B0%E7%A0%81%E4%BA%A7%E5%93%81.mp4',
    duration: '1:08',
    category: 'satisfying',
    asmrType: 'Digital Cutting',
    featured: false,
    createdAt: '2024-12-26T13:30:00Z',
    viewCount: 2134,
    tags: ['digital', 'cutting', 'electronic', 'text-to-video', 'ai-asmr-video']
  },
  {
    id: 'glass-fruit-cutting-1',
    title: 'Glass Fruit Cutting ASMR - Google Veo AI',
    description: 'Beautiful glass fruit cutting with crystalline knife sounds created by Google Veo3 AI. Perfect ASMR generator content for YouTube shorts and TikTok videos. Features satisfying visual effects and professional sound design for relaxation.',
    prompt: 'Realistic 4K footage close-up of a knife rapidly cutting a [COLOR] [MATERIAL] [OBJECT] on a wooden cuttingboard. It slices it multiple times, each slice falls over as the knife moves to the next. The inside of the [OBJECT] is also [MATERIAL]. The sound is ASMR style.',
    thumbnailUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87%E5%89%B2%E7%8E%BB%E7%92%83%E6%B0%B4%E6%9E%9C.mp4',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87%E5%89%B2%E7%8E%BB%E7%92%83%E6%B0%B4%E6%9E%9C.mp4',
    duration: '0:58',
    category: 'crystal',
    asmrType: 'Glass Cutting',
    featured: false,
    createdAt: '2024-12-26T12:45:00Z',
    viewCount: 1789,
    tags: ['glass', 'fruit', 'crystal', 'cutting', 'knife', 'google-veo', 'ai-video']
  },
  {
    id: 'gorilla-stone-cutting-1',
    title: 'Gorilla Stone Cutting ASMR - AI Video Generator',
    description: 'Unique stone cutting experience with natural textures created by AI video maker. Perfect for YouTube shorts and satisfying content creation. Features primal stone cutting sounds and realistic textures generated with Google AI technology.',
    prompt: 'A photorealistic scene unfolds in a lush green forest with mossy ground. A massive, white-furred ape-like creature (resembling a Yeti or white gorilla) sits purposefully behind a flat, dark stone slab resting on a tree stump. A sharp knife and an irregular dark rock are placed on the slab. The creature\'s large, powerful hand carefully grasps the gleaming knife, then precisely positions and presses the blade down, cleanly slicing the rock in half. Its hands then gently pull apart the two halves of the rock, dramatically revealing a surprising sight: a small, live, brown-grey mouse sitting calmly on the stone slab between the separated rock pieces. The mouse appears unfazed as the creature\'s gaze shifts to the viewer with a curious or knowing expression, while faint mouse squeaks are heard. The lighting is natural, highlighting the detailed textures of the fur, rock, and mouse.',
    thumbnailUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E7%8C%A9%E7%8C%A9%E5%88%87%E7%9F%B3%E5%A4%B4.mp4',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E7%8C%A9%E7%8C%A9%E5%88%87%E7%9F%B3%E5%A4%B4.mp4',
    duration: '1:15',
    category: 'nature',
    asmrType: 'Stone Cutting',
    featured: false,
    createdAt: '2024-12-26T11:20:00Z',
    viewCount: 1623,
    tags: ['stone', 'nature', 'gorilla', 'cutting', 'ai-videos', 'satisfying']
  },
  {
    id: 'bread-golden-sauce-1',
    title: 'Bread Golden Sauce ASMR Al Video',
    description: 'Satisfying bread spreading with rich golden sauce created using advanced AI video maker. Perfect TikTok shorts and YouTube content with smooth food textures and ASMR sound effects generated by Google Veo3 technology.',
    prompt: 'A glass cup pours out many round golden particles made of gold onto the surface of a slice of toast, and then a knife is used to spread the golden particles into a paste. The sound is ASMR style.',
    thumbnailUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E9%9D%A2%E5%8C%85%E6%B6%82%E6%8A%B9%E9%BB%84%E9%87%91%E9%85%B1.mp4',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E9%9D%A2%E5%8C%85%E6%B6%82%E6%8A%B9%E9%BB%84%E9%87%91%E9%85%B1.mp4',
    duration: '1:02',
    category: 'texture',
    asmrType: 'Food Texture',
    featured: false,
    createdAt: '2024-12-26T10:30:00Z',
    viewCount: 2456,
    tags: ['bread', 'sauce', 'food', 'texture', 'ai-asmr-video', 'tiktok-shorts']
  },
  {
    id: 'mc-block-cutting-1',
    title: 'Minecraft Block Cutting ASMR - Veo3 AI Generator',
    description: 'Satisfying Minecraft block cutting with perfect geometric precision created by Google Veo3 AI. Ideal for YouTube shorts and TikTok videos. Features crisp sound effects and pixel-perfect cutting animations for gaming ASMR content.',
    prompt: 'Realistic 4K footage close-up of a knife rapidly cutting a Minecraft style [OBJECT] block on a wooden cuttingboard. It slices it multiple times, each slice falls over as the knife moves to the next. The inside of the [OBJECT] is also Minecraft style. The sound is Minecraft style [OBJECT] style.',
    thumbnailUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87mc%E6%96%B9%E5%9D%97.mp4',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87mc%E6%96%B9%E5%9D%97.mp4',
    duration: '0:45',
    category: 'satisfying',
    asmrType: 'Block Cutting',
    featured: true,
    createdAt: '2024-12-26T15:30:00Z',
    viewCount: 1856,
    tags: ['minecraft', 'cutting', 'satisfying', 'blocks', 'veo3-ai', 'gaming-asmr']
  }
];

// 获取首页展示的视频（featured=true的前N个）
export const getFeaturedVideos = (limit: number = 6): ShowcaseVideo[] => {
  return showcaseVideos
    .filter(video => video.featured)
    .slice(0, limit);
};

// 根据分类获取视频
export const getVideosByCategory = (category: VideoCategory): ShowcaseVideo[] => {
  return showcaseVideos.filter(video => video.category === category);
};

// 获取最新视频
export const getLatestVideos = (limit: number = 6): ShowcaseVideo[] => {
  return showcaseVideos
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, limit);
}; 