import { ShowcaseVideo, VideoCategory } from './video-types';

// 腾讯云ASMR视频集合 - Google Veo3 AI生成的专业ASMR视频
export const showcaseVideos: ShowcaseVideo[] = [
  {
    id: 'planet-cutting-1',
    title: 'Planet Cutting ASMR - AI Video Generator',
    description: 'Experience cosmic planet cutting with Google Veo3 AI technology. Perfect for YouTube shorts and TikTok videos. This AI-generated ASMR video features mesmerizing space textures and otherworldly sound effects created with advanced text-to-video AI.',
    thumbnailUrl: 'https://via.placeholder.com/400x300/8b5cf6/7c3aed?text=Planet+Cut',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87%E5%89%B2%E6%98%9F%E7%90%83%E8%A1%8C%E6%98%9F.mp4',
    duration: '1:05',
    category: 'satisfying',
    asmrType: 'Planet Cutting',
    featured: true,
    createdAt: '2024-12-27T15:00:00Z',
    viewCount: 2847,
    tags: ['planet', 'space', 'cosmic', 'cutting', 'veo3', 'ai-video', 'youtube-shorts', 'tiktok']
  },
  {
    id: 'glass-vegetable-cutting-1',
    title: 'Glass Vegetable Cutting ASMR - AI ASMR Generator',
    description: 'Delicate glass vegetable cutting created with AI video maker technology. Perfect satisfying content for TikTok shorts and YouTube videos. Features crystal-clear knife cutting sounds and beautiful translucent textures generated by Google Veo3 AI.',
    thumbnailUrl: 'https://via.placeholder.com/400x300/22d3ee/0891b2?text=Glass+Veggie',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87%E5%89%B2%E7%8E%BB%E7%92%83%E8%94%AC%E8%8F%9C.mp4',
    duration: '0:58',
    category: 'crystal',
    asmrType: 'Glass Cutting',
    featured: true,
    createdAt: '2024-12-27T14:30:00Z',
    viewCount: 3156,
    tags: ['glass', 'vegetable', 'crystal', 'cutting', 'knife', 'ai-asmr', 'youtube-shorts', 'tiktok-shorts']
  },
  {
    id: 'cosmic-cutting-1',
    title: 'Cosmic Nebula Cutting ASMR - Google Veo3 AI',
    description: 'Experience mesmerizing cosmic nebula cutting created with Google Veo3 AI technology. Perfect for YouTube shorts and TikTok videos. Features ethereal space sounds and stunning visual effects. This AI-generated ASMR video showcases the best of what AI ASMR can create with advanced text-to-video technology.',
    thumbnailUrl: 'https://via.placeholder.com/400x300/a855f7/9333ea?text=Cosmic+Cut',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87%E5%89%B2%E6%98%9F%E4%BA%91%E3%80%81%E4%B9%8C%E4%BA%91.mp4',
    duration: '1:10',
    category: 'satisfying',
    asmrType: 'Cosmic Cutting',
    featured: true,
    createdAt: '2024-12-27T11:00:00Z',
    viewCount: 1337,
    tags: ['cosmic', 'nebula', 'cutting', 'space', 'veo3-asmr', 'ai-videos', 'youtube-shorts', 'tiktok']
  },
  {
    id: 'squeeze-toy-1',
    title: 'Squeeze Toy ASMR - AI Video Maker',
    description: 'Satisfying squeeze toy ASMR created with best AI video generator. Perfect for YouTube shorts and TikTok content creation. Features soft textures and gentle pressure sound effects generated by Google AI technology for ultimate relaxation.',
    thumbnailUrl: 'https://via.placeholder.com/400x300/fbbf24/f59e0b?text=Squeeze+Toy',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E6%8D%8F%E6%8D%8F%E4%B9%90.mp4',
    duration: '0:52',
    category: 'texture',
    asmrType: 'Squeeze Toy',
    featured: true,
    createdAt: '2024-12-26T14:00:00Z',
    viewCount: 1456,
    tags: ['squeeze', 'texture', 'soft', 'ai-video-maker', 'youtube-shorts']
  },
  {
    id: 'digital-product-cutting-1',
    title: 'Digital Product Cutting ASMR - Text to Video AI',
    description: 'Precise cutting sounds of digital devices created with advanced AI video generator. Perfect for creating AI videos and TikTok shorts. Features crisp electronic textures and satisfying knife cutting sounds generated by Google Veo3.',
    thumbnailUrl: 'https://via.placeholder.com/400x300/3b82f6/1d4ed8?text=Digital+Cut',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87%E6%95%B0%E7%A0%81%E4%BA%A7%E5%93%81.mp4',
    duration: '1:08',
    category: 'satisfying',
    asmrType: 'Digital Cutting',
    featured: true,
    createdAt: '2024-12-26T13:30:00Z',
    viewCount: 2134,
    tags: ['digital', 'cutting', 'electronic', 'text-to-video', 'ai-asmr-video']
  },
  {
    id: 'glass-fruit-cutting-1',
    title: 'Glass Fruit Cutting ASMR - Google Veo AI',
    description: 'Beautiful glass fruit cutting with crystalline knife sounds created by Google Veo3 AI. Perfect ASMR generator content for YouTube shorts and TikTok videos. Features satisfying visual effects and professional sound design for relaxation.',
    thumbnailUrl: 'https://via.placeholder.com/400x300/06b6d4/0891b2?text=Glass+Fruit',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87%E5%89%B2%E7%8E%BB%E7%92%83%E6%B0%B4%E6%9E%9C.mp4',
    duration: '0:58',
    category: 'crystal',
    asmrType: 'Glass Cutting',
    featured: false,
    createdAt: '2024-12-26T12:45:00Z',
    viewCount: 1789,
    tags: ['glass', 'fruit', 'crystal', 'cutting', 'knife', 'google-veo', 'ai-video']
  },
  {
    id: 'gorilla-stone-cutting-1',
    title: 'Gorilla Stone Cutting ASMR - AI Video Generator',
    description: 'Unique stone cutting experience with natural textures created by AI video maker. Perfect for YouTube shorts and satisfying content creation. Features primal stone cutting sounds and realistic textures generated with Google AI technology.',
    thumbnailUrl: 'https://via.placeholder.com/400x300/84cc16/65a30d?text=Stone+Cut',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E7%8C%A9%E7%8C%A9%E5%88%87%E7%9F%B3%E5%A4%B4.mp4',
    duration: '1:15',
    category: 'nature',
    asmrType: 'Stone Cutting',
    featured: false,
    createdAt: '2024-12-26T11:20:00Z',
    viewCount: 1623,
    tags: ['stone', 'nature', 'gorilla', 'cutting', 'ai-videos', 'satisfying']
  },
  {
    id: 'bread-golden-sauce-1',
    title: 'Bread Golden Sauce ASMR - Best AI Video Generator',
    description: 'Satisfying bread spreading with rich golden sauce created using advanced AI video maker. Perfect TikTok shorts and YouTube content with smooth food textures and ASMR sound effects generated by Google Veo3 technology.',
    thumbnailUrl: 'https://via.placeholder.com/400x300/fbbf24/d97706?text=Golden+Sauce',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E9%9D%A2%E5%8C%85%E6%B6%82%E6%8A%B9%E9%BB%84%E9%87%91%E9%85%B1.mp4',
    duration: '1:02',
    category: 'texture',
    asmrType: 'Food Texture',
    featured: false,
    createdAt: '2024-12-26T10:30:00Z',
    viewCount: 2456,
    tags: ['bread', 'sauce', 'food', 'texture', 'ai-asmr-video', 'tiktok-shorts']
  },
  {
    id: 'mc-block-cutting-1',
    title: 'Minecraft Block Cutting ASMR - Veo3 AI Generator',
    description: 'Satisfying Minecraft block cutting with perfect geometric precision created by Google Veo3 AI. Ideal for YouTube shorts and TikTok videos. Features crisp sound effects and pixel-perfect cutting animations for gaming ASMR content.',
    thumbnailUrl: 'https://via.placeholder.com/400x300/4ade80/16a34a?text=MC+Block+Cut',
    videoUrl: 'https://aiasmr-video-1363880159.cos.ap-guangzhou.myqcloud.com/%E5%88%87mc%E6%96%B9%E5%9D%97.mp4',
    duration: '0:45',
    category: 'satisfying',
    asmrType: 'Block Cutting',
    featured: true,
    createdAt: '2024-12-26T15:30:00Z',
    viewCount: 1856,
    tags: ['minecraft', 'cutting', 'satisfying', 'blocks', 'veo3-ai', 'gaming-asmr']
  }
];

// 获取首页展示的视频（featured=true的前N个）
export const getFeaturedVideos = (limit: number = 6): ShowcaseVideo[] => {
  return showcaseVideos
    .filter(video => video.featured)
    .slice(0, limit);
};

// 根据分类获取视频
export const getVideosByCategory = (category: VideoCategory): ShowcaseVideo[] => {
  return showcaseVideos.filter(video => video.category === category);
};

// 获取最新视频
export const getLatestVideos = (limit: number = 6): ShowcaseVideo[] => {
  return showcaseVideos
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, limit);
}; 